default_platform(:ios)
firebase_app_id = "1:1008921881187:ios:02a2a355f68098947c6656"

lane :build do
    get_certificates()
    get_provisioning_profile(adhoc: true, force: true)
    build_app(export_method: "ad-hoc")
end

lane :download_udids do
    firebase_app_distribution_get_udids(
        app: firebase_app_id,
        output_file: "udids.txt",
    )
end

lane :add_new_devices do
    register_devices(devices_file: "udids.txt")
end

lane :distribute do
    download_udids
    add_new_devices
    build
    firebase_app_distribution(
        app: firebase_app_id,
        release_notes: "Try out this app!",
    )
end